# Generated by Django 4.2.30 on 2026-08-28 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição / Diretrizes')),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='aberta', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('criada_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Texto da Matéria')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias_escritas', to=settings.AUTH_USER_MODEL, verbose_name='Autor (Repórter)')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='core.pauta', verbose_name='Pauta de Origem')),
            ],
        ),
    ]
