# Generated by Django 4.2.30 on 2026-08-29 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='retranca',
            field=models.CharField(default='SEM_RETRANCA', max_length=50, verbose_name='Retranca'),
        ),
    ]
