# Generated by Django 4.2.30 on 2026-08-29 16:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_pauta_retranca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pauta',
            name='descricao',
        ),
        migrations.RemoveField(
            model_name='pauta',
            name='titulo',
        ),
        migrations.AddField(
            model_name='pauta',
            name='data',
            field=models.DateField(blank=True, null=True, verbose_name='Data'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='direcionamento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Direcionamento'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='hora',
            field=models.TimeField(blank=True, null=True, verbose_name='Hora'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='informacoes',
            field=models.TextField(default='', verbose_name='Informações'),
        ),
        migrations.AlterField(
            model_name='pauta',
            name='criada_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pautas_criadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pauta',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pauta',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('em_andamento', 'Em Andamento'), ('concluida', 'Concluída')], default='aberta', max_length=20),
        ),
    ]
