# Generated by Django 4.2.30 on 2026-08-29 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pauta_descricao_remove_pauta_titulo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pauta',
            name='hora',
        ),
        migrations.AlterField(
            model_name='pauta',
            name='direcionamento',
            field=models.TextField(default='', verbose_name='Direcionamento'),
        ),
        migrations.CreateModel(
            name='AgendaPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('horario', models.TimeField(blank=True, null=True)),
                ('entrevistados', models.TextField(blank=True, null=True)),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas', to='core.pauta')),
            ],
        ),
    ]
