# Generated by Django 4.2.30 on 2026-08-29 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0004_remove_pauta_hora_alter_pauta_direcionamento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pauta',
            name='data_edicao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data da última edição'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='editado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas_editadas', to=settings.AUTH_USER_MODEL, verbose_name='Editado por'),
        ),
        migrations.AddField(
            model_name='pauta',
            name='reporter_atribuido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pautas_atribuidas', to=settings.AUTH_USER_MODEL, verbose_name='Direcionar para Repórter'),
        ),
    ]
