# Generated by Django 4.2.30 on 2026-08-31 11:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_pauta_data_edicao_pauta_editado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='status_edicao',
            field=models.CharField(choices=[('nao_editada', 'Não Editada'), ('editada', 'Editada')], default='nao_editada', max_length=20, verbose_name='Edição'),
        ),
        migrations.AddField(
            model_name='materia',
            name='status_exibicao',
            field=models.CharField(choices=[('gaveta', 'Gaveta'), ('exibida', 'Exibida')], default='gaveta', max_length=20, verbose_name='Exibição'),
        ),
        migrations.AlterField(
            model_name='materia',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='materia',
            name='data_atualizacao',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='pauta',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='materia', to='core.pauta'),
        ),
    ]
